/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { AppContext as ctx } from "./../../server/context"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  LoginInput: { // input type
    password: string; // String!
    username: string; // String!
  }
}

export interface NexusGenEnums {
  Publicity: "friends" | "private" | "public"
  Specificity: "athletic" | "cardio" | "general" | "hypertrophy" | "strength"
  TrainingLevel: "advanced" | "beginner" | "intermediate"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  AppError: { // root type
    createdAt: string; // String!
    message: string; // String!
    name: string; // String!
  }
  Exercise: { // root type
    description: string; // String!
    id: string; // ID!
    reps?: number | null; // Int
    rpe?: number | null; // Int
    sets?: number | null; // Int
  }
  Mutation: {};
  Program: { // root type
    complimentary?: boolean | null; // Boolean
    id: string; // ID!
    name: string; // String!
    publicity: NexusGenEnums['Publicity']; // Publicity!
    specificity: NexusGenEnums['Specificity'][]; // [Specificity!]!
    tags: string[]; // [String!]!
    trainingLevel?: NexusGenEnums['TrainingLevel'] | null; // TrainingLevel
  }
  Query: {};
  User: { // root type
    email: string; // String!
    id: string; // ID!
    token?: string | null; // String
    username: string; // String!
  }
  UserResponse: { // root type
    error?: NexusGenRootTypes['AppError'] | null; // AppError
    user?: NexusGenRootTypes['User'] | null; // User
  }
  Workout: { // root type
    id: string; // ID!
    name: string; // String!
    specificity: NexusGenEnums['Specificity'][]; // [Specificity!]!
    tags: string[]; // [String!]!
    trainingLevel: NexusGenEnums['TrainingLevel']; // TrainingLevel!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  AppError: { // field return type
    createdAt: string; // String!
    message: string; // String!
    name: string; // String!
  }
  Exercise: { // field return type
    description: string; // String!
    id: string; // ID!
    reps: number | null; // Int
    rpe: number | null; // Int
    sets: number | null; // Int
  }
  Mutation: { // field return type
    login: NexusGenRootTypes['UserResponse']; // UserResponse!
  }
  Program: { // field return type
    complimentary: boolean | null; // Boolean
    id: string; // ID!
    name: string; // String!
    publicity: NexusGenEnums['Publicity']; // Publicity!
    specificity: NexusGenEnums['Specificity'][]; // [Specificity!]!
    tags: string[]; // [String!]!
    trainingLevel: NexusGenEnums['TrainingLevel'] | null; // TrainingLevel
    workouts: NexusGenRootTypes['Workout'][]; // [Workout!]!
  }
  Query: { // field return type
    me: NexusGenRootTypes['User'] | null; // User
  }
  User: { // field return type
    email: string; // String!
    id: string; // ID!
    token: string | null; // String
    username: string; // String!
  }
  UserResponse: { // field return type
    error: NexusGenRootTypes['AppError'] | null; // AppError
    user: NexusGenRootTypes['User'] | null; // User
  }
  Workout: { // field return type
    id: string; // ID!
    name: string; // String!
    specificity: NexusGenEnums['Specificity'][]; // [Specificity!]!
    tags: string[]; // [String!]!
    trainingLevel: NexusGenEnums['TrainingLevel']; // TrainingLevel!
  }
}

export interface NexusGenFieldTypeNames {
  AppError: { // field return type name
    createdAt: 'String'
    message: 'String'
    name: 'String'
  }
  Exercise: { // field return type name
    description: 'String'
    id: 'ID'
    reps: 'Int'
    rpe: 'Int'
    sets: 'Int'
  }
  Mutation: { // field return type name
    login: 'UserResponse'
  }
  Program: { // field return type name
    complimentary: 'Boolean'
    id: 'ID'
    name: 'String'
    publicity: 'Publicity'
    specificity: 'Specificity'
    tags: 'String'
    trainingLevel: 'TrainingLevel'
    workouts: 'Workout'
  }
  Query: { // field return type name
    me: 'User'
  }
  User: { // field return type name
    email: 'String'
    id: 'ID'
    token: 'String'
    username: 'String'
  }
  UserResponse: { // field return type name
    error: 'AppError'
    user: 'User'
  }
  Workout: { // field return type name
    id: 'ID'
    name: 'String'
    specificity: 'Specificity'
    tags: 'String'
    trainingLevel: 'TrainingLevel'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    login: { // args
      input: NexusGenInputs['LoginInput']; // LoginInput!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: ctx;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}